<a href="https://colab.research.google.com/github/MaxSchock/Test/blob/main/2_3_2_Working_with_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Introducción a los Vectores y Matrices

$$
\begin{equation}
\begin{pmatrix}
x_{11} & . & x_{1m}\\
. & . & .\\
x_{n1} & . & x_{nm}
\end{pmatrix}
\end{equation}
$$

In [ ]:
import numpy as np

In [ ]:
# Para comprobar la versión
print(np.__version__)

1.21.6


***
$$
\begin{equation}
X=\begin{pmatrix}
1 & 0 & 4\\
3 & 3 & 1
\end{pmatrix},
Y=\begin{pmatrix}
2 & 5\\
1 & 1\\
3 & 2
\end{pmatrix}
\end{equation}
$$

In [ ]:
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
x1 * x2

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
np.multiply(y, x)

ValueError: ignored

# Basics of NumPy Array Object

In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

In [ ]:
print("We just create a ", type(x))

In [ ]:
print("Our template has shape as" ,x.shape)

In [ ]:
print("Total size is",x.size)

In [ ]:
print("The dimension of our array is " ,x.ndim)

In [ ]:
print("Data type of elements are",x.dtype)

In [ ]:
print("It consumes",x.nbytes,"bytes")

In [ ]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.float)
print(x)
print(x.nbytes)

In [ ]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.complex)
print(x)
print(x.nbytes)

In [ ]:
x = np.array([[1,2,3],[4,-5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

In [ ]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 comsues",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 comsues",x.nbytes, "bytes")

In [ ]:
x_copy = np.array(x, dtype = np.float)
x_copy 

In [ ]:
x_copy_int = x_copy.astype(np.int)
x_copy_int

In [ ]:
x_copy

In [ ]:
Data_Cancer = np.random.rand(100000,100)
print(type(Data_Cancer))
print(Data_Cancer.dtype)
print(Data_Cancer.nbytes)
Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print(Data_Cancer_New.nbytes)

In [ ]:
Data_Cancer

# NumPy Array Operations

In [ ]:
import numpy as np

In [ ]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

In [ ]:
my_array +2

In [ ]:
my_array -1

In [ ]:
my_array *2

In [ ]:
my_array /2

In [ ]:
second_array = np.zeros(4) + 3
second_array 

In [ ]:
my_array - second_array 

In [ ]:
second_array / my_array 

In [ ]:
second_array = np.ones(4)+3
second_array

In [ ]:
my_array - second_array 

In [ ]:
second_array / my_array 

In [ ]:
second_array = np.identity(4)
second_array

In [ ]:
second_array = np.identity(4)+3
second_array

In [ ]:
my_array - second_array 

In [ ]:
second_array / my_array 

In [ ]:
x = np.arange(3,7,0.5)
x

In [ ]:
x = np.linspace(1.2, 40.5, num=20)
x

In [ ]:
np.geomspace(1, 625, num=5)

In [ ]:
np.logspace(3, 4, num=5)

In [ ]:
np.logspace(np.log10(3) , np.log10(4) , num=5)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

In [ ]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
np.array_equal(x,y)

In [ ]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x < y 

In [ ]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_or(x,y)

In [ ]:
np.logical_and(x,y)

In [ ]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

---


$$
e = 2,718281...
$$

In [ ]:
x = np.array([1, 2, 3,4 ])
np.exp(x)

In [ ]:
np.log(x)

In [ ]:
np.sin(x)

In [ ]:
x = np.arange(9)
x

In [ ]:
x = np.arange(9).reshape((3, 3))
x

In [ ]:
x.T

In [ ]:
x = np.arange(6).reshape(2,3)
x

In [ ]:
x.T

In [ ]:
x = np.arange(9).reshape((3,3))
x

In [ ]:
np.sum(x)

In [ ]:
np.amin(x)

In [ ]:
np.amax(x)

In [ ]:
np.amin(x, axis=0)

In [ ]:
np.amin(x, axis=1)

In [ ]:
np.percentile(x, 80)

In [ ]:
x = np.array([1,-21,3,-3])
np.argmax(x)

In [ ]:
np.argmin(x)

In [ ]:
x = np.array([[2, 3, 5], [20, 12, 4]])
x

In [ ]:
np.mean(x)

In [ ]:
np.mean(x, axis=0)

In [ ]:
np.mean(x, axis=1)

In [ ]:
np.median(x)

In [ ]:
np.std(x)

# Working with Multidimensional Arrays

In [ ]:
import numpy as np

In [ ]:
c = np.ones((4, 4))
c*c

In [ ]:
c.dot(c)

In [ ]:
y = np.arange(15).reshape(3,5) 
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
print('X = ', x)
print('\n')
print('Y = ', y)
new_array

In [ ]:
y = np.arange(15).reshape(5,3) 
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y,x))
new_array

In [ ]:
import numpy.ma as ma
x = np.arange(6)
print(x, x.mean())
masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
masked_array.mean()

In [ ]:
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
x

In [ ]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

# Indexing, Slicing, Reshaping, Resizing, Broadcasting

In [ ]:
import numpy as np

In [ ]:
x = ["USA","France", "Germany","England"]
x[2]

In [ ]:
x = ('USA',3,"France",4)
x[2]

In [ ]:
x = np.arange(10)
x

In [ ]:
x[5]

In [ ]:
x[-2]

In [ ]:
x[2:8]

In [ ]:
x[:]

In [ ]:
x[2:8:2]

In [ ]:
x = np.reshape(np.arange(16),(4,4))
x

In [ ]:
x[1:3]

In [ ]:
x[:,1:3]

In [ ]:
x[1:3,1:3]

In [ ]:
x = np.reshape(np.arange(16),(4,4))
x

In [ ]:
x[[0,1,2],[0,1,3]]

In [ ]:
x = np.arange(16).reshape(4,4)
x

In [ ]:
np.resize(x,(2,2))

In [ ]:
np.resize(x,(6,6))

In [ ]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
x+y

In [ ]:
x = np.ones(16).reshape(4,4)
y = np.arange(4)
x*y

In [ ]:
x = np.arange(4).reshape(2,2)
x

In [ ]:
y = np.arange(2).reshape(1,2)
y

In [ ]:
x*y